M48
; DRILL file {KiCad 7.0.7} date Thu Apr  4 13:45:23 2024
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-04-04T13:45:23+09:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.7
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1063
%
G90
G05
T1
X4.765Y-3.7231
X4.765Y-4.6287
X7.0485Y-3.7231
X7.0485Y-4.6287
T0
M30
